Integrate ByteSlice into bliss
BU-DiSC/bliss_benchmark pull request #48
Opened 2024-12-05 17:51 UTC by altramarine

2025-02-06 16:47 UTC, ramananeesh requested changes
@altramarine please address the comments and re-request the review once ready.

2025-02-14 06:10 UTC, altramarine commented
The get(start, end) function is not correct in main repo, the return should be a newly created bitmap indicating which row is selected in range scan not a bool. I think we canfirst squash and merge this before merging other scan accelorators.

2025-02-14 06:14 UTC, ramananeesh commented
> The get(start, end) function is not correct in main repo, the return should be a newly created bitmap indicating which row is selected in range scan not a bool. I think we canfirst squash and merge this before merging other scan accelorators.

So there are two ways to approach range query functions - one is to return the bool indicating that we did find some results, and the other is the returned entries themselves in a map/array. 

Since this is a benchmarking tool, we "assume" correctness of the code we are integrating. Hence, we do not need to return the bitmap of the results, a bool will suffice.

2025-02-14 06:37 UTC, altramarine commented
I think I have resolved everything and it is ready to merge with main

2025-02-14 14:45 UTC, ephoris approved these changes
LGTM!

2025-02-14 14:47 UTC, ramananeesh approved these changes
LGTM 👍

2025-02-21 07:31 UTC, merged